# Generated by Django 5.1.2 on 2024-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifysession',
            name='expires_at',
            field=models.BigIntegerField(),
        ),
    ]
