# Generated by Django 5.1.2 on 2024-10-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_spotifysession_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifySession',
        ),
    ]
